<?php return array (
  'all_in_one' => false,
  'main_package' => 'All',
  'path' => './system/packages/',
  'packages' => 
  array (
    'Core' => 
    array (
      'paths' => 
      array (
        0 => './system/library/Zend/Db.php',
        1 => './system/library/Zend/Db/Adapter/Abstract.php',
        2 => './system/library/Zend/Db/Adapter/Mysqli.php',
        3 => './system/library/Db/Adapter/Mysqli.php',
        4 => './system/library/Filter.php',
        5 => './system/library/Template.php',
        6 => './system/library/Request.php',
        7 => './system/library/Response.php',
        8 => './system/library/Resource.php',
        9 => './system/library/Config.php',
        10 => './system/library/Config/Abstract.php',
        11 => './system/library/Config/Simple.php',
        12 => './system/library/Config/File.php',
        13 => './system/library/Config/File/Array.php',
        14 => './system/library/Lang.php',
        15 => './system/app/Application.php',
        16 => './system/app/Page.php',
        17 => './system/library/Db/Object/Config.php',
        18 => './system/app/Eventmanager.php',
        19 => './system/library/Db/Object/Event/Manager.php',
        20 => './system/library/Db/Object/Store.php',
        21 => './system/library/Model.php',
        22 => './system/app/Controller.php',
        23 => './system/app/Router.php',
        24 => './system/library/Registry.php',
        25 => './system/library/Store.php',
        26 => './system/library/Store/Interface.php',
        27 => './system/library/Store/Local.php',
        28 => './system/library/Zend/Db/Profiler.php',
        29 => './system/app/Cache/Manager.php',
        30 => './system/app/Externals/Expert.php',
        31 => './system/library/Db/Object/Config/Translator.php',
        32 => './system/library/Db/Manager/Interface.php',
        33 => './system/app/Db/Manager.php',
      ),
      'active' => true,
      'checksum' => '29eeeec7ad21ee82bfccb169ba10aca2',
      'fchecksum' => '0ba60cc6b31c97d92fed1a68fdeb3d4f',
    ),
    'Frontend' => 
    array (
      'paths' => 
      array (
        0 => './system/app/Blockmanager.php',
        1 => './system/app/Frontend/Router.php',
        2 => './system/app/Frontend/Controller.php',
        3 => './system/app/Model/Blocks.php',
        4 => './system/app/Model/Page.php',
        5 => './system/app/Model/Blockmapping.php',
        6 => './system/app/Model/Menu/Item.php',
        7 => './system/app/Block.php',
        8 => './system/app/Block/Menu.php',
        9 => './system/app/Block/Menu/Top.php',
        10 => './system/app/Block/Menu/Footer.php',
      ),
      'active' => true,
      'checksum' => '100025df970759011c281f040265bec9',
      'fchecksum' => 'd39c4b9eaa965f76eec118b472f8a8e0',
    ),
    'Backend' => 
    array (
      'paths' => 
      array (
        0 => './system/app/Backend/Controller.php',
        1 => './system/app/Backend/Router.php',
        6 => './system/library/Security/Csrf.php',
        7 => './system/app/Backend/Modules/Manager.php',
      ),
      'active' => true,
      'checksum' => '8b0eaaf608771421ea9309123d1db78e',
      'fchecksum' => '2735b9a92e3ce9609c97e37cb858d4d0',
    ),
    'Ext' => 
    array (
      'paths' => 
      array (
        0 => './system/library/Ext/Code.php',
        1 => './system/library/Ext.php',
        2 => './system/library/Ext/Grid.php',
        3 => './system/library/Ext/Factory.php',
        4 => './system/library/Ext/Grid/Column.php',
        5 => './system/library/Ext/Grid/Column/Action.php',
        6 => './system/library/Ext/Grid/Column/Boolean.php',
        7 => './system/library/Ext/Grid/Column/Date.php',
        8 => './system/library/Ext/Grid/Column/Number.php',
        9 => './system/library/Ext/Grid/Column/Template.php',
        10 => './system/library/Ext/Model.php',
        11 => './system/library/Ext/Model/Association.php',
        12 => './system/library/Ext/Model/Field.php',
        13 => './system/library/Ext/Model/Validation.php',
        14 => './system/library/Ext/Object.php',
        15 => './system/library/Ext/Property.php',
        16 => './system/library/Ext/Property/Button.php',
        17 => './system/library/Ext/Property/Component.php',
        18 => './system/library/Ext/Property/Container.php',
        19 => './system/library/Ext/Property/Data/Proxy.php',
        20 => './system/library/Ext/Property/Data/Proxy/Ajax.php',
        21 => './system/library/Ext/Property/Data/Proxy/Client.php',
        22 => './system/library/Ext/Property/Data/Proxy/Direct.php',
        23 => './system/library/Ext/Property/Data/Proxy/Jsonp.php',
        24 => './system/library/Ext/Property/Data/Proxy/Localstorage.php',
        25 => './system/library/Ext/Property/Data/Proxy/Memory.php',
        26 => './system/library/Ext/Property/Data/Proxy/Rest.php',
        27 => './system/library/Ext/Property/Data/Proxy/Server.php',
        28 => './system/library/Ext/Property/Data/Proxy/Sessionstorage.php',
        29 => './system/library/Ext/Property/Data/Proxy/Webstorage.php',
        30 => './system/library/Ext/Property/Data/Reader.php',
        31 => './system/library/Ext/Property/Data/Reader/Array.php',
        32 => './system/library/Ext/Property/Data/Reader/Json.php',
        33 => './system/library/Ext/Property/Data/Reader/Xml.php',
        34 => './system/library/Ext/Property/Data/Writer.php',
        35 => './system/library/Ext/Property/Data/Writer/Json.php',
        36 => './system/library/Ext/Property/Data/Writer/Xml.php',
        37 => './system/library/Ext/Property/Form.php',
        38 => './system/library/Ext/Property/Form/Checkboxgroup.php',
        39 => './system/library/Ext/Property/Form/Field/Base.php',
        40 => './system/library/Ext/Property/Form/Field/Trigger.php',
        41 => './system/library/Ext/Property/Form/Field/Picker.php',
        42 => './system/library/Ext/Property/Form/Field/Spinner.php',
        43 => './system/library/Ext/Property/Form/Field/Checkbox.php',
        44 => './system/library/Ext/Property/Form/Field/Date.php',
        45 => './system/library/Ext/Property/Form/Field/Field.php',
        46 => './system/library/Ext/Property/Form/Field/File.php',
        47 => './system/library/Ext/Property/Form/Field/Htmleditor.php',
        48 => './system/library/Ext/Property/Form/Field/Number.php',
        49 => './system/library/Ext/Property/Form/Field/Radio.php',
        50 => './system/library/Ext/Property/Form/Field/Text.php',
        51 => './system/library/Ext/Property/Form/Field/Textarea.php',
        52 => './system/library/Ext/Property/Form/Field/Time.php',
        53 => './system/library/Ext/Property/Form/Fieldset.php',
        54 => './system/library/Ext/Property/Form/Radiogroup.php',
        55 => './system/library/Ext/Property/Grid.php',
        56 => './system/library/Ext/Property/View/View.php',
        57 => './system/library/Ext/Property/View/Table.php',
        58 => './system/library/Ext/Property/Grid/View.php',
        59 => './system/library/Ext/Property/Grid/Column.php',
        60 => './system/library/Ext/Property/Grid/Column/Action.php',
        61 => './system/library/Ext/Property/Grid/Column/Boolean.php',
        62 => './system/library/Ext/Property/Grid/Column/Date.php',
        63 => './system/library/Ext/Property/Grid/Column/Number.php',
        64 => './system/library/Ext/Property/Grid/Column/Template.php',
        65 => './system/library/Ext/Property/Model.php',
        66 => './system/library/Ext/Property/Panel.php',
        67 => './system/library/Ext/Property/Store.php',
        68 => './system/library/Ext/Property/Table.php',
        69 => './system/library/Ext/Property/Tabpanel.php',
        70 => './system/library/Ext/Property/Toolbar/Item.php',
        71 => './system/library/Ext/Property/Toolbar/Paging.php',
        72 => './system/library/Ext/Property/Toolbar/Textitem.php',
        73 => './system/library/Ext/Property/Toolbar/Toolbar.php',
        74 => './system/library/Ext/Property/Window.php',
        75 => './system/library/Ext/Virtual.php',
        76 => './system/library/Ext/Component/Renderer/System/Publish.php',
        77 => './system/library/Ext/Config.php',
        78 => './system/library/Ext/Docked.php',
        79 => './system/library/Ext/Property/Component/Window/System/Crud/Vc.php',
        80 => './system/library/Ext/Property/Docked.php',
        81 => './system/library/Ext/Property/Form/Field/Combobox.php',
        82 => './system/library/Ext/Property/Form/Field/Display.php',
        83 => './system/library/Ext/Property/Form/Fieldcontainer.php',
        84 => './system/library/Ext/Property/Toolbar.php',
        85 => './system/library/Ext/Property/Toolbar/Fill.php',
        86 => './system/library/Ext/Property/Toolbar/Separator.php',
        87 => './system/library/Ext/Property/Toolbar/Spacer.php',
        88 => './system/library/Ext/Store.php',
        89 => './system/library/Ext/Component/Field/System/Dictionary.php',
        90 => './system/library/Ext/Component/Renderer.php',
        91 => './system/library/Ext/Component/Renderer/System/Checkbox.php',
        92 => './system/library/Ext/Component/Renderer/System/Creator.php',
        93 => './system/library/Ext/Component/Renderer/System/Multiline.php',
        94 => './system/library/Ext/Component/Renderer/System/Updater.php',
        95 => './system/library/Ext/Component/Renderer/System/Version.php',
        96 => './system/library/Ext/Component/Field.php',
        97 => './system/library/Ext/Component/Field/System/Searchfield.php',
        98 => './system/library/Ext/Component/Filter.php',
        99 => './system/library/Ext/Component/Renderer/System/Date/Ru.php',
        100 => './system/library/Ext/Component/Renderer/System/Money/Us.php',
        101 => './system/library/Ext/Property/Component/Field/System/Dictionary.php',
        102 => './system/library/Ext/Property/Component/Field/System/Searchfield.php',
        103 => './system/library/Ext/Property/Component/Filter.php',
        104 => './system/library/Ext/Property/Component/Window/System/Crud.php',
        105 => './system/library/Ext/Component/Field/System/Medialibhtml.php',
        106 => './system/library/Ext/Component/Field/System/Medialibitem.php',
        107 => './system/library/Ext/Component/Field/System/Related.php',
        108 => './system/library/Ext/Property/Component/Field/System/Medialibhtml.php',
        109 => './system/library/Ext/Property/Component/Field/System/Medialibitem.php',
        110 => './system/library/Ext/Property/Component/Field/System/Related.php',
        111 => './system/library/Ext/Button.php',
        112 => './system/library/Ext/Component/Abstract/Renderer/Dictionary.php',
        113 => './system/library/Ext/Grid/Column/Action/Button.php',
        114 => './system/library/Ext/Property/Data/Abstractstore.php',
        115 => './system/library/Ext/Property/Data/Store.php',
        116 => './system/library/Ext/Property/Data/Store/Tree.php',
        117 => './system/library/Ext/Property/Grid/Column/Action/Button.php',
        118 => './system/library/Ext/Property/Tree.php',
      ),
      'active' => true,
      'checksum' => '4264466cef523a01d058fa9a61403f2e',
      'fchecksum' => '3145df6efea1056d3db6c26f2b209cfc',
    ),
    'Cache' => 
    array (
      'paths' => 
      array (
        0 => './system/library/Cache.php',
        1 => './system/library/Cache/Abstract.php',
        2 => './system/library/Cache/Interface.php',
        3 => './system/library/Cache/Memcache.php',
      ),
      'active' => true,
      'checksum' => 'c38f234936dc6a3f323b8011ca32ac4d',
      'fchecksum' => '346def317eeaca4bb83e4d200643cce8',
    ),
    'Ext_Events' => 
    array (
      'paths' => 
      array (
        0 => './system/library/Ext/Events.php',
        1 => './system/library/Ext/Events/Button.php',
        2 => './system/library/Ext/Events/Component.php',
        3 => './system/library/Ext/Events/Component/Window/System/Crud.php',
        4 => './system/library/Ext/Events/Component/Window/System/Crud/Vc.php',
        5 => './system/library/Ext/Events/Container.php',
        6 => './system/library/Ext/Events/Form.php',
        7 => './system/library/Ext/Events/Form/Field/Base.php',
        8 => './system/library/Ext/Events/Form/Field/Field.php',
        9 => './system/library/Ext/Events/Form/Field/Text.php',
        10 => './system/library/Ext/Events/Form/Field/Picker.php',
        11 => './system/library/Ext/Events/Form/Checkboxgroup.php',
        12 => './system/library/Ext/Events/Form/Field/Checkbox.php',
        13 => './system/library/Ext/Events/Form/Field/Combobox.php',
        14 => './system/library/Ext/Events/Form/Field/Date.php',
        15 => './system/library/Ext/Events/Form/Field/Display.php',
        16 => './system/library/Ext/Events/Form/Field/File.php',
        17 => './system/library/Ext/Events/Form/Field/Htmleditor.php',
        18 => './system/library/Ext/Events/Form/Field/Number.php',
        19 => './system/library/Ext/Events/Form/Field/Radio.php',
        20 => './system/library/Ext/Events/Form/Field/Spinner.php',
        21 => './system/library/Ext/Events/Form/Field/Textarea.php',
        22 => './system/library/Ext/Events/Form/Field/Time.php',
        23 => './system/library/Ext/Events/Form/Fieldcontainer.php',
        24 => './system/library/Ext/Events/Form/Fieldset.php',
        25 => './system/library/Ext/Events/Form/Radiogroup.php',
        26 => './system/library/Ext/Events/Grid.php',
        27 => './system/library/Ext/Events/Grid/Column.php',
        28 => './system/library/Ext/Events/Grid/Column/Action.php',
        29 => './system/library/Ext/Events/Grid/Column/Boolean.php',
        30 => './system/library/Ext/Events/Grid/Column/Date.php',
        31 => './system/library/Ext/Events/Grid/Column/Number.php',
        32 => './system/library/Ext/Events/Grid/Column/Template.php',
        33 => './system/library/Ext/Events/Panel.php',
        34 => './system/library/Ext/Events/Store.php',
        35 => './system/library/Ext/Events/Table.php',
        36 => './system/library/Ext/Events/Tabpanel.php',
        37 => './system/library/Ext/Events/Toolbar.php',
        38 => './system/library/Ext/Events/Toolbar/Fill.php',
        39 => './system/library/Ext/Events/Toolbar/Item.php',
        40 => './system/library/Ext/Events/Toolbar/Paging.php',
        41 => './system/library/Ext/Events/Toolbar/Separator.php',
        42 => './system/library/Ext/Events/Toolbar/Spacer.php',
        43 => './system/library/Ext/Events/Toolbar/Textitem.php',
        44 => './system/library/Ext/Events/Window.php',
        45 => './system/library/Ext/Events/Data/Abstractstore.php',
        46 => './system/library/Ext/Events/Data/Store.php',
        47 => './system/library/Ext/Events/Data/Store/Tree.php',
        48 => './system/library/Ext/Events/Grid/Column/Action/Button.php',
        49 => './system/library/Ext/Events/Tree.php',
      ),
      'active' => true,
      'checksum' => 'f641ba0fb8d8c63ab235e25c77c3ee5f',
      'fchecksum' => '7aa79240fdc9d28ea18a540aa1a7347a',
    ),
    'Designer' => 
    array (
      'paths' => 
      array (
        0 => './system/library/Designer/Factory.php',
        1 => './system/library/Designer/Project.php',
        2 => './system/library/Designer/Project/Events.php',
        3 => './system/library/Designer/Storage.php',
        4 => './system/library/Designer/Storage/Adapter/Abstract.php',
        5 => './system/library/Designer/Storage/Adapter/File.php',
      ),
      'active' => true,
      'checksum' => 'e83189a64083b55d81517afa7d2ce6cf',
      'fchecksum' => '128ad4a0031e5bb1e686c03c2a81002c',
    ),
    'User' => 
    array (
      'paths' => 
      array (
        0 => './system/library/User/Interface.php',
        1 => './system/app/Model/Permissions.php',
        2 => './system/app/Model/User.php',
        3 => './system/app/User.php',
        4 => './system/app/User/Admin.php',
      ),
      'active' => true,
      'checksum' => '09ecbb077dac87f3a3caeda05a15be78',
      'fchecksum' => '5531fb4cd4696f892e340c78b86bc87d',
    ),
    'Db_Select' => 
    array (
      'paths' => 
      array (
        0 => './system/library/Db/Select.php',
        1 => './system/library/Zend/Db/Statement/Interface.php',
        2 => './system/library/Zend/Db/Statement.php',
        3 => './system/library/Zend/Db/Statement/Mysqli.php',
      ),
      'active' => true,
      'checksum' => '2339acf5505aaf648c147950851e4030',
      'fchecksum' => 'c4119fbde798c90641afbcdf3d3828f8',
    ),
  ),
); 