<?php
/**
 * Filestorage UI controller
 */
use Dvelum\Config;
use Dvelum\Orm;
use Dvelum\Model;
use Dvelum\App\Controller;

class Backend_Filestorage_Controller extends Dvelum\App\Backend\Api\Controller
{
    protected $canViewObjects = ['user'];

    public function indexAction()
    {
        $certStorage = Model::factory('Filestorage')->getStorage();
        $this->resource->addInlineJs('app.filestorageConfig = '.json_encode($certStorage->getConfig()->get('uploader_config')).';');
        parent::indexAction();
    }

    public function initListeners()
    {
        parent::initListeners(); // TODO: Change the autogenerated stub

        $apiRequest = $this->apiRequest;

        $this->eventManager->on(Controller\EventManager::BEFORE_LIST, function(Controller\Event $event) use ($apiRequest){
            $date = $apiRequest->getFilter('date');
            if(!empty($date)){
                $date = date('Y-m-d', strtotime($date));
                $dateFilter = new \Db_Select_Filter('date' , array($date.' 00:00:00', $date.' 23:59:59') , \Db_Select_Filter::BETWEEN);
                $apiRequest->addFilter('date', $dateFilter);

            }else{
                $apiRequest->resetFilter('date');
            }
        });

        $this->eventManager->on(Controller\EventManager::AFTER_LIST,[$this, 'prepareList']);
    }

    public function prepareList(Controller\Event $event)
    {
        $data = & $event->getData()->data;

        if(empty($data)){
            return;
        }

        $userIds = \Utils::fetchCol('user_id' , $data);
        $userData = [];

        if(!empty($userIds)){
            return;
        }

        $userData = Model::factory('User')->getList(false , array('id'=>$userIds) , array('id','name'));
        if(!empty($userData)){
            $userData = \Utils::rekey('id' , $userData);
        }

        foreach($data as $k=>&$v)
        {
            if(isset($userData[$v['user_id']])){
                $v['user_name'] = $userData[$v['user_id']]['name'];
            }else{
                $v['user_name'] = '';
            }
        }unset($v);

    }

    /**
     * Download file from FileStorage
     */
    public function downloadAction()
    {
        $fileId = intval($this->request->getPart(3));

        if(!$fileId){
            $this->response->redirect('/');
        }

        try{
            $file = Orm\Object::factory('Filestorage' , $fileId);
        }catch (Exception $e){
            $this->response->redirect('/');
        }

        $storage = Model::factory('Filestorage')->getStorage();
        $storageConfig = $storage->getConfig()->__toArray();

        $storagePath = $storageConfig['filepath']. $file->get('path');

        if (!file_exists($storagePath)) {
            $this->response->put($this->lang->get('FILE_NOT_FOUND'));
            $this->response->send();
        }

        header('Content-Description: File Transfer');
       // header('Content-Type: application/octet-stream');
        header('Content-Disposition: attachment; filename=' . str_replace(' ' ,'_' , $file->get('name')));

        switch($storageConfig['download']['type']){
            case 'native' :
                readfile($storagePath);
                break;
            case 'apache' :
                $filePath = $storageConfig['redirect_path']. $file->get('path');
                header('X-Sendfile: ' . $filePath);
                break;
            case 'nginx' :
                $filePath = $storageConfig['redirect_path']. $file->get('path');
                header('X-Accel-Redirect: ' . $filePath);
                break;
        }
        exit();
    }

    /**
     * file upload
     */
    public function uploadAction()
    {
       $this->checkCanEdit();

       $files = Request::files();

        if (!isset($files['file']) || empty($files['file'])){
            $this->response->error($this->lang->get('FILL_FORM'));
        }

        /**
         * @var \Filestorage_Abstract $fileStorage
         */
        $fileStorage = Model::factory('Filestorage')->getStorage();

        $files = $fileStorage->upload();

        if (empty($files)) {
            $this->response->error($this->lang->get('CANT_EXEC'));
        }

        $this->response->success();
    }

    /**
     * Delete object
     * Sends JSON reply in the result and
     * closes the application
     */
    public function deleteAction()
    {
        $this->checkCanDelete();
        $id = $this->request->post('id' , 'integer' , false);

        if(!$id)
            $this->response->error($this->lang->get('WRONG_REQUEST'));

        try{
            $object = Orm\Object::factory($this->objectName , $id);
        }catch(Exception $e){
            $this->response->error($this->lang->get('WRONG_REQUEST'));
        }

        $acl = $object->getAcl();
        if($acl && !$acl->canDelete($object)){
            $this->response->error($this->lang->get('CANT_DELETE'));
        }

        $fileStorage = Model::factory('Filestorage')->getStorage();

        if(!$fileStorage->remove($id)){
            $this->response->error($this->lang->get('CANT_EXEC'));
        }

        Response::jsonSuccess();
    }
} 