<?php
return array(
	'columns'=>3,
	'items'=>array(
		'topblocks'=>array(
			'colspan'=>3,
			'isElContainer'=>true,
            'width'=>600,
            'height'=>80,
		),
		'content'=>array(
			'colspan'=>2,
			'isElContainer'=>false,
		    'width'=>450,
            'height'=>200
		),
		'rightblocks'=>array(
			'colspan'=>1,
			'rowspan'=>2,
			'isElContainer'=>true,
		    'width'=>150,
            'height'=>280
		),
		'centerleft'=>array(
			'isElContainer'=>true,
			'width'=>225,
			'height'=>80
		),
		'centerright'=>array(
			'isElContainer'=>true,
			'width'=>225,
			'height'=>80
		),
		'bottomblocks'=>array(
			'colspan'=>3,
			'isElContainer'=>true,
			'width'=>600,
            'height'=>80
		),
		'footerblocks'=>array(
			'colspan'=>3,
			'isElContainer'=>true,
		    'width'=>600,
            'height'=>80
		)
	 )
);